services:
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data

  api:
    restart: always
    build: .
    depends_on:
      - db
    container_name: api
    ports:
      - 8000:8000
    env_file: .env

volumes:
  db: